[project]
name = "smelly-weather"
version = "1.0.0"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["test"]
addopts = "-v"